CREATE MEMORY TABLE "PUBLIC"."ONG"(
    "ID" INTEGER DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_DCC965DD_D94B_4FFC_9F50_A026DB2FF8B3" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_DCC965DD_D94B_4FFC_9F50_A026DB2FF8B3",
    "CITY" VARCHAR(255),
    "EMAIL" VARCHAR(255),
    "NAME" VARCHAR(255),
    "UF" VARCHAR(255),
    "WHATSAPP" VARCHAR(255),
    "USER_ONG_ID" INTEGER
);
ALTER TABLE "PUBLIC"."ONG" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("ID");