CREATE MEMORY TABLE "PUBLIC"."USER_ONG"(
    "ID" INTEGER DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_77BDA87E_3BBB_4C09_9F92_B0C87BCC5AB4" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_77BDA87E_3BBB_4C09_9F92_B0C87BCC5AB4",
    "PASSWORD" VARCHAR(255),
    "USERNAME" VARCHAR(255) NOT NULL
);
ALTER TABLE "PUBLIC"."USER_ONG" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1E" PRIMARY KEY("ID");