insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (1, 'Little Rock', 'rshale0@spotify.com', 'Tempsoft', 'AR', '501-156-0023');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (2, 'Washington', 'rmackniely1@google.com.hk', 'Matsoft', 'DC', '202-704-8769');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (3, 'San Diego', 'wlougheid2@deviantart.com', 'Biodex', 'CA', '619-987-4269');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (4, 'Duluth', 'tsterte3@unblog.fr', 'Daltfresh', 'MN', '218-865-4465');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (5, 'Washington', 'vbread4@weibo.com', 'Veribet', 'DC', '202-516-5111');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (6, 'Montgomery', 'koverington5@prnewswire.com', 'Flowdesk', 'AL', '334-588-6947');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (7, 'West Palm Beach', 'pplaster6@examiner.com', 'Redhold', 'FL', '954-828-1270');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (8, 'Amarillo', 'hzisneros7@bloglines.com', 'Voltsillam', 'TX', '806-245-1391');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (9, 'San Antonio', 'jtuffield8@goodreads.com', 'Opela', 'TX', '210-380-4680');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (10, 'Washington', 'etallis9@squarespace.com', 'Cardify', 'DC', '202-246-1968');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (11, 'Maple Plain', 'iguenya@hp.com', 'Stronghold', 'MN', '763-547-6656');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (12, 'Charleston', 'tmcginnyb@patch.com', 'Domainer', 'WV', '304-562-4266');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (13, 'San Jose', 'nbouldec@amazonaws.com', 'Fix San', 'CA', '408-783-9443');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (14, 'Jackson', 'mtrusdaled@ifeng.com', 'Zaam-Dox', 'MS', '601-671-8509');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (15, 'Fort Lauderdale', 'zmeindle@shinystat.com', 'Tres-Zap', 'FL', '754-304-7562');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (16, 'Lansing', 'tbaynef@hhs.gov', 'Alphazap', 'MI', '517-164-2203');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (17, 'Buffalo', 'tambrozikg@phpbb.com', 'Zaam-Dox', 'NY', '716-377-1459');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (18, 'Syracuse', 'twolverh@theatlantic.com', 'Keylex', 'NY', '315-800-1133');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (19, 'Albuquerque', 'rraynhami@flavors.me', 'Matsoft', 'NM', '505-143-1251');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (20, 'Washington', 'bmynottj@nymag.com', 'Kanlam', 'DC', '202-306-5153');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (21, 'Panama City', 'rkeatk@hp.com', 'Lotstring', 'FL', '850-262-7227');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (22, 'San Diego', 'tcamilil@reference.com', 'Voyatouch', 'CA', '619-585-2949');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (23, 'Philadelphia', 'pliquorishm@zdnet.com', 'Prodder', 'PA', '215-240-1084');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (24, 'Jacksonville', 'vlavern@google.fr', 'Transcof', 'FL', '904-134-1639');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (25, 'Las Vegas', 'tpargetero@boston.com', 'Tin', 'NV', '702-419-8912');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (26, 'San Antonio', 'dkelnerp@theglobeandmail.com', 'Zathin', 'TX', '210-585-5657');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (27, 'Washington', 'cbeneditoq@scribd.com', 'Viva', 'DC', '202-913-8158');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (28, 'Atlanta', 'cwroer@sina.com.cn', 'Biodex', 'GA', '770-193-9749');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (29, 'Harrisburg', 'kgrassots@mapy.cz', 'Tres-Zap', 'PA', '717-183-7531');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (30, 'Amarillo', 'ogremanet@shop-pro.jp', 'Bitchip', 'TX', '806-149-1237');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (31, 'Pittsburgh', 'pnewburnu@biglobe.ne.jp', 'Zathin', 'PA', '412-889-7936');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (32, 'New Bedford', 'ashanahanv@canalblog.com', 'Overhold', 'MA', '508-355-0218');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (33, 'Indianapolis', 'dmckibbinw@ifeng.com', 'Ronstring', 'IN', '317-584-5744');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (34, 'Silver Spring', 'hscaicex@deviantart.com', 'Stim', 'MD', '240-387-9208');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (35, 'Anchorage', 'pjordisony@mediafire.com', 'Toughjoyfax', 'AK', '907-736-4058');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (36, 'Washington', 'dhadwinz@marketwatch.com', 'Duobam', 'DC', '202-189-2859');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (37, 'San Rafael', 'mcheyney10@google.co.jp', 'Tampflex', 'CA', '415-997-6608');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (38, 'Omaha', 'pvinter11@cargocollective.com', 'Asoka', 'NE', '402-623-2662');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (39, 'Jackson', 'gjolin12@acquirethisname.com', 'Andalax', 'MS', '601-891-5967');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (40, 'Irving', 'ysommerland13@vistaprint.com', 'Zaam-Dox', 'TX', '972-809-6929');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (41, 'Austin', 'slukovic14@uol.com.br', 'Stringtough', 'TX', '512-101-7324');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (42, 'Oakland', 'dcapehorn15@buzzfeed.com', 'Namfix', 'CA', '510-449-9260');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (43, 'Fort Lauderdale', 'cgimenez16@technorati.com', 'Cardguard', 'FL', '954-271-7943');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (44, 'Moreno Valley', 'janyon17@desdev.cn', 'Treeflex', 'CA', '951-511-1446');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (45, 'Austin', 'larnowitz18@geocities.com', 'It', 'TX', '512-179-9353');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (46, 'Minneapolis', 'rdougherty19@sakura.ne.jp', 'Temp', 'MN', '612-733-6067');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (47, 'Newark', 'pmckerrow1a@cbslocal.com', 'Bytecard', 'NJ', '862-663-7278');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (48, 'Sacramento', 'xdenisot1b@vinaora.com', 'Tres-Zap', 'CA', '916-181-5481');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (49, 'Saint Paul', 'wcarletti1c@comsenz.com', 'Trippledex', 'MN', '651-626-2875');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (50, 'Springfield', 'bbutterwick1d@netvibes.com', 'Y-Solowarm', 'MA', '413-743-2016');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (51, 'Cincinnati', 'mkelemen1e@noaa.gov', 'Tres-Zap', 'OH', '513-440-4007');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (52, 'Missoula', 'bmacklin1f@statcounter.com', 'Matsoft', 'MT', '406-731-0024');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (53, 'Minneapolis', 'bdelaeglise1g@yahoo.com', 'Zamit', 'MN', '952-336-2123');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (54, 'Birmingham', 'mmowsdale1h@cnet.com', 'Ventosanzap', 'AL', '205-538-8168');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (55, 'Fresno', 'mmatussow1i@si.edu', 'Ventosanzap', 'CA', '559-588-3688');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (56, 'El Paso', 'church1j@freewebs.com', 'Cookley', 'TX', '915-712-0543');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (57, 'Lexington', 'rfroud1k@plala.or.jp', 'Bytecard', 'KY', '859-711-4019');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (58, 'Hollywood', 'gwalshaw1l@github.io', 'Daltfresh', 'FL', '305-880-5419');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (59, 'Boston', 'rmussen1m@reddit.com', 'Lotlux', 'MA', '318-715-8305');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (60, 'Miami', 'kvasser1n@xrea.com', 'Wrapsafe', 'FL', '786-292-4036');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (61, 'Phoenix', 'hfearenside1o@newsvine.com', 'Flexidy', 'AZ', '602-928-5330');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (62, 'El Paso', 'pmcgeneay1p@baidu.com', 'Asoka', 'TX', '915-758-9377');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (63, 'Bethesda', 'mfuller1q@google.com', 'Zathin', 'MD', '240-499-2377');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (64, 'Merrifield', 'jgartell1r@phpbb.com', 'Tin', 'VA', '571-646-4526');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (65, 'Richmond', 'billyes1s@w3.org', 'Voltsillam', 'CA', '510-601-8615');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (66, 'Saint Louis', 'wpringuer1t@google.com', 'Keylex', 'MO', '314-846-4039');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (67, 'Vancouver', 'dtrundell1u@sbwire.com', 'Bytecard', 'WA', '360-364-3903');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (68, 'Sacramento', 'mboumphrey1v@statcounter.com', 'Mat Lam Tam', 'CA', '916-646-9082');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (69, 'Philadelphia', 'dbuttrick1w@moonfruit.com', 'Cardify', 'PA', '215-438-6856');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (70, 'El Paso', 'aslight1x@usnews.com', 'Viva', 'TX', '915-103-3066');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (71, 'Evansville', 'dragbourne1y@oakley.com', 'Matsoft', 'IN', '812-190-5861');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (72, 'Cape Coral', 'jgudde1z@nps.gov', 'Biodex', 'FL', '239-758-9781');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (73, 'Hamilton', 'lwoolfitt20@cocolog-nifty.com', 'Keylex', 'OH', '937-557-4331');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (74, 'Orlando', 'kmackro21@spotify.com', 'Job', 'FL', '407-378-7962');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (75, 'Buffalo', 'czecchetti22@usatoday.com', 'Regrant', 'NY', '716-790-7077');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (76, 'San Jose', 'blamberteschi23@edublogs.org', 'Tres-Zap', 'CA', '408-812-8349');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (77, 'Fresno', 'smcgiffin24@flavors.me', 'Zamit', 'CA', '209-945-5948');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (78, 'Saint Paul', 'fprestland25@alexa.com', 'Biodex', 'MN', '651-893-6145');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (79, 'Jacksonville', 'bblaydes26@cdbaby.com', 'Tresom', 'FL', '904-821-5303');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (80, 'Colorado Springs', 'ydansie27@twitpic.com', 'Lotstring', 'CO', '719-542-0588');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (81, 'Lakeland', 'pgasnoll28@about.me', 'Rank', 'FL', '863-989-0094');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (82, 'Little Rock', 'btroak29@admin.ch', 'Subin', 'AR', '501-427-0902');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (83, 'Savannah', 'lgeake2a@omniture.com', 'Konklux', 'GA', '912-436-9747');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (84, 'Newark', 'sbonde2b@seattletimes.com', 'Keylex', 'NJ', '973-956-3320');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (85, 'Bakersfield', 'aspurdens2c@businessinsider.com', 'Solarbreeze', 'CA', '661-197-0440');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (86, 'Minneapolis', 'imasterton2d@ustream.tv', 'Y-find', 'MN', '612-250-5820');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (87, 'Abilene', 'nmatterdace2e@aol.com', 'Stim', 'TX', '325-466-8250');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (88, 'El Paso', 'fpittem2f@webeden.co.uk', 'Tres-Zap', 'TX', '915-797-6618');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (89, 'Anaheim', 'rmcdoual2g@mayoclinic.com', 'Cookley', 'CA', '714-862-2120');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (90, 'Tampa', 'showsin2h@ebay.com', 'Stronghold', 'FL', '813-595-3149');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (91, 'Honolulu', 'gstranger2i@wunderground.com', 'Quo Lux', 'HI', '808-949-6849');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (92, 'Modesto', 'hwhitrod2j@twitpic.com', 'Treeflex', 'CA', '559-198-8471');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (93, 'Grand Rapids', 'hbowlas2k@dmoz.org', 'Stringtough', 'MI', '616-294-1839');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (94, 'Macon', 'agartin2l@hostgator.com', 'Sub-Ex', 'GA', '478-178-2392');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (95, 'Bakersfield', 'amulhill2m@ow.ly', 'Sub-Ex', 'CA', '661-890-4335');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (96, 'Santa Cruz', 'leaglestone2n@w3.org', 'Y-find', 'CA', '831-362-8980');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (97, 'Inglewood', 'eglasspool2o@go.com', 'Voyatouch', 'CA', '323-110-9679');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (98, 'Duluth', 'lsquibbs2p@bigcartel.com', 'Ronstring', 'GA', '678-871-1024');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (99, 'Charlottesville', 'kproger2q@walmart.com', 'Quo Lux', 'VA', '434-144-6247');
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP) values (100, 'Akron', 'charner2r@bbc.co.uk', 'Home Ing', 'OH', '234-344-7168');
