insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (1, 'Wichita', 'kdoyly0@dagondesign.com', 'Matsoft', 'KS', '(316) 1682102', 1);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (2, 'Northridge', 'vwellstead1@smugmug.com', 'Zamit', 'CA', '(818) 3102971', 2);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (3, 'Charlotte', 'mtalby2@forbes.com', 'Fixflex', 'NC', '(704) 4364323', 3);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (4, 'Longview', 'lnaden3@bbb.org', 'Overhold', 'TX', '(903) 4301522', 4);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (5, 'Richmond', 'epurple4@skyrock.com', 'Prodder', 'VA', '(540) 7731527', 5);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (6, 'Nashville', 'squant5@bloglovin.com', 'Temp', 'TN', '(615) 4986356', 6);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (7, 'Pittsburgh', 'rburtenshaw6@cpanel.net', 'Opela', 'PA', '(412) 8310137', 7);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (8, 'Port Saint Lucie', 'sglasscoe7@ucsd.edu', 'Flowdesk', 'FL', '(772) 7761696', 8);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (9, 'Lincoln', 'rcampsall8@blogger.com', 'It', 'NE', '(402) 7473985', 9);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (10, 'Tallahassee', 'jfeldbaum9@reuters.com', 'Temp', 'FL', '(850) 5206157', 10);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (11, 'Detroit', 'jmcilhaggaa@apple.com', 'Sonair', 'MI', '(313) 4077446', 11);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (12, 'New Brunswick', 'ctremolletb@bloglines.com', 'Pannier', 'NJ', '(732) 2760573', 12);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (13, 'Peoria', 'ltaillc@home.pl', 'Stringtough', 'IL', '(309) 4932845', 13);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (14, 'Winston Salem', 'dparradined@timesonline.co.uk', 'Toughjoyfax', 'NC', '(336) 1184342', 14);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (15, 'Atlanta', 'wparmane@amazonaws.com', 'Cardify', 'GA', '(404) 1419595', 15);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (16, 'Saint Louis', 'nrieff@slideshare.net', 'Sub-Ex', 'MO', '(314) 7729617', 16);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (17, 'Nashville', 'sballing@mozilla.com', 'Domainer', 'TN', '(615) 3029278', 17);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (18, 'Seattle', 'msilberh@nih.gov', 'Greenlam', 'WA', '(360) 8731409', 18);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (19, 'Hattiesburg', 'kblannini@de.vu', 'Prodder', 'MS', '(601) 9412493', 19);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (20, 'Cincinnati', 'bmcilhattonj@naver.com', 'Overhold', 'OH', '(513) 7827260', 20);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (21, 'Tulsa', 'csummertonk@seesaa.net', 'Alphazap', 'OK', '(918) 4131164', 21);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (22, 'Santa Cruz', 'mbelvinl@imdb.com', 'Stim', 'CA', '(831) 3449592', 22);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (23, 'Lakeland', 'hchasteym@ucoz.com', 'Keylex', 'FL', '(863) 3438564', 23);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (24, 'Anaheim', 'ygyenesn@typepad.com', 'Konklab', 'CA', '(714) 9461261', 24);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (25, 'Chicago', 'fbrackstoneo@shinystat.com', 'Subin', 'IL', '(312) 8517319', 25);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (26, 'Corpus Christi', 'spurcellp@ifeng.com', 'Tempsoft', 'TX', '(361) 1785616', 26);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (27, 'San Francisco', 'tdeenerq@dyndns.org', 'Flexidy', 'CA', '(415) 2371692', 27);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (28, 'Columbus', 'tillidger@npr.org', 'Konklux', 'OH', '(614) 8909514', 28);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (29, 'Largo', 'rreeves@bing.com', 'Cookley', 'FL', '(727) 9212766', 29);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (30, 'San Francisco', 'rbentingt@linkedin.com', 'Gembucket', 'CA', '(415) 4075011', 30);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (31, 'Portland', 'cvonoertzenu@behance.net', 'Flexidy', 'OR', '(971) 7636880', 31);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (32, 'Hialeah', 'ctweedyv@hud.gov', 'Bytecard', 'FL', '(786) 1125600', 32);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (33, 'Winston Salem', 'klettsw@wikia.com', 'Bitchip', 'NC', '(336) 9901147', 33);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (34, 'Hartford', 'lthairsx@netlog.com', 'Greenlam', 'CT', '(860) 8628599', 34);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (35, 'Rockville', 'dmartinay@1688.com', 'Bitwolf', 'MD', '(301) 2971954', 35);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (36, 'Fresno', 'rbatistez@techcrunch.com', 'Y-Solowarm', 'CA', '(209) 4820056', 36);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (37, 'Young America', 'aaleksashin10@illinois.edu', 'Gembucket', 'MN', '(952) 1258224', 37);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (38, 'Wilmington', 'lmadgewick11@miibeian.gov.cn', 'Vagram', 'NC', '(910) 5123531', 38);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (39, 'Milwaukee', 'ckilday12@icq.com', 'Tresom', 'WI', '(414) 1479247', 39);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (40, 'Little Rock', 'cayce13@theatlantic.com', 'Alphazap', 'AR', '(501) 5660296', 40);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (41, 'Newton', 'sdrivers14@goo.gl', 'Toughjoyfax', 'MA', '(508) 7805913', 41);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (42, 'Galveston', 'csmeeton15@flavors.me', 'Temp', 'TX', '(281) 2299139', 42);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (43, 'Scottsdale', 'sfaulkener16@theglobeandmail.com', 'Zamit', 'AZ', '(480) 3683777', 43);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (44, 'Portland', 'gbrahm17@plala.or.jp', 'Daltfresh', 'OR', '(503) 2491772', 44);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (45, 'Memphis', 'bduckinfield18@cpanel.net', 'Flexidy', 'TN', '(901) 6905431', 45);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (46, 'Orlando', 'mschuler19@spiegel.de', 'Y-find', 'FL', '(407) 6793128', 46);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (47, 'San Antonio', 'gmoiser1a@sourceforge.net', 'Viva', 'TX', '(210) 6040920', 47);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (48, 'Fresno', 'dbruster1b@java.com', 'Rank', 'CA', '(559) 1917903', 48);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (49, 'Atlanta', 'hreedshaw1c@sphinn.com', 'Bigtax', 'GA', '(404) 5761239', 49);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (50, 'Tulsa', 'fworwood1d@t.co', 'Quo Lux', 'OK', '(918) 4109251', 50);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (51, 'Waco', 'rflanigan1e@nydailynews.com', 'Bigtax', 'TX', '(254) 5621963', 51);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (52, 'Humble', 'nshakspeare1f@cloudflare.com', 'Job', 'TX', '(713) 3373362', 52);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (53, 'Fresno', 'njanouch1g@google.pl', 'Bigtax', 'CA', '(559) 5251061', 53);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (54, 'Tulsa', 'lwellwood1h@soup.io', 'Solarbreeze', 'OK', '(918) 9018265', 54);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (55, 'Saint Joseph', 'kpeschmann1i@stumbleupon.com', 'Viva', 'MO', '(816) 9031875', 55);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (56, 'Silver Spring', 'epfaff1j@ning.com', 'Bigtax', 'MD', '(301) 1837856', 56);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (57, 'Staten Island', 'nhryniewicki1k@about.com', 'Alphazap', 'NY', '(718) 2483577', 57);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (58, 'Denton', 'zgamble1l@sfgate.com', 'Home Ing', 'TX', '(682) 8886800', 58);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (59, 'Austin', 'plawdham1m@reuters.com', 'Tampflex', 'TX', '(512) 3894505', 59);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (60, 'Paterson', 'sbriscow1n@printfriendly.com', 'Otcom', 'NJ', '(201) 3263219', 60);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (61, 'Grand Forks', 'roconnolly1o@1688.com', 'Ventosanzap', 'ND', '(701) 5827391', 61);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (62, 'Bakersfield', 'ghefferan1p@w3.org', 'Tempsoft', 'CA', '(661) 4086904', 62);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (63, 'Miami', 'wcrackel1q@tmall.com', 'Voyatouch', 'FL', '(786) 8435316', 63);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (64, 'Sandy', 'dmathevet1r@1688.com', 'Flexidy', 'UT', '(801) 2665189', 64);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (65, 'Long Beach', 'djeandin1s@1688.com', 'Voyatouch', 'CA', '(562) 1635090', 65);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (66, 'Washington', 'cvayro1t@miibeian.gov.cn', 'Fix San', 'DC', '(202) 5320824', 66);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (67, 'Fort Wayne', 'csmallcomb1u@dyndns.org', 'Transcof', 'IN', '(260) 4590510', 67);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (68, 'Colorado Springs', 'ckinningley1v@illinois.edu', 'Alphazap', 'CO', '(719) 6113654', 68);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (69, 'West Hartford', 'cclout1w@virginia.edu', 'Temp', 'CT', '(860) 2600044', 69);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (70, 'Huntington', 'acabell1x@netlog.com', 'Stronghold', 'WV', '(304) 1876045', 70);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (71, 'Tampa', 'ppennini1y@live.com', 'Fix San', 'FL', '(813) 1775299', 71);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (72, 'Orlando', 'psnoddin1z@miibeian.gov.cn', 'Stronghold', 'FL', '(407) 2656997', 72);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (73, 'Miami', 'afawdry20@constantcontact.com', 'Flexidy', 'FL', '(305) 2215649', 73);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (74, 'San Antonio', 'bmckall21@dagondesign.com', 'Sonair', 'TX', '(210) 1038635', 74);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (75, 'Little Rock', 'rhallows22@independent.co.uk', 'Cookley', 'AR', '(501) 9428170', 75);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (76, 'Norcross', 'gduddan23@nymag.com', 'Temp', 'GA', '(770) 1883692', 76);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (77, 'Spokane', 'ageipel24@bigcartel.com', 'Solarbreeze', 'WA', '(509) 8140188', 77);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (78, 'Silver Spring', 'dbranwhite25@i2i.jp', 'Tampflex', 'MD', '(240) 5539073', 78);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (79, 'Hartford', 'mlissaman26@storify.com', 'Tempsoft', 'CT', '(860) 6803576', 79);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (80, 'Athens', 'ejoysey27@oakley.com', 'Zamit', 'GA', '(706) 4192753', 80);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (81, 'Washington', 'jmacmeekan28@oakley.com', 'Stim', 'DC', '(202) 3466148', 1);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (82, 'Greensboro', 'sledstone29@epa.gov', 'Y-Solowarm', 'NC', '(336) 6308124', 2);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (83, 'Richmond', 'iartinstall2a@mit.edu', 'Wrapsafe', 'VA', '(804) 6576392', 3);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (84, 'Santa Ana', 'hcunnane2b@blog.com', 'Job', 'CA', '(714) 9619870', 4);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (85, 'Washington', 'dmosco2c@joomla.org', 'Tresom', 'DC', '(202) 2604586', 5);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (86, 'Abilene', 'dfedoronko2d@dailymotion.com', 'Job', 'TX', '(325) 7306056', 6);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (87, 'Houston', 'rbrittlebank2e@usda.gov', 'Mat Lam Tam', 'TX', '(832) 3785294', 7);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (88, 'Brea', 'eeddington2f@ifeng.com', 'Wrapsafe', 'CA', '(818) 1428324', 8);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (89, 'Saint Petersburg', 'ttincombe2g@dailymotion.com', 'Aerified', 'FL', '(727) 2478078', 9);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (90, 'Boise', 'callcock2h@zdnet.com', 'Greenlam', 'ID', '(208) 8386463', 10);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (91, 'Fort Pierce', 'bdutnell2i@admin.ch', 'Cardify', 'FL', '(772) 5973934', 11);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (92, 'San Francisco', 'jbaggally2j@clickbank.net', 'Hatity', 'CA', '(415) 9338354', 12);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (93, 'Dallas', 'ckeigher2k@house.gov', 'Alphazap', 'TX', '(214) 4543788', 13);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (94, 'New York City', 'gwindrum2l@simplemachines.org', 'Zoolab', 'NY', '(212) 3492244', 14);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (95, 'Dallas', 'ymeininger2m@nasa.gov', 'Fintone', 'TX', '(469) 8990489', 15);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (96, 'Meridian', 'jmccorley2n@canalblog.com', 'Trippledex', 'MS', '(601) 1292384', 16);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (97, 'Memphis', 'kcamp2o@msn.com', 'Prodder', 'TN', '(901) 5222485', 17);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (98, 'Bismarck', 'delleton2p@senate.gov', 'It', 'ND', '(701) 9758132', 18);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (99, 'Iowa City', 'rgrelka2q@ted.com', 'Biodex', 'IA', '(319) 3512836', 19);
insert into ONG (ID, CITY, EMAIL, NAME, UF, WHATSAPP, USER_ONG_ID) values (100, 'Charleston', 'ebottle2r@nps.gov', 'Bitchip', 'WV', '(304) 1089869', 20);
